import type { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: 'AdE App Example',
  description: 'Generated by AdE Starter Kit',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it"> {/* Impostare lang="it" come da standard AGID */}
      <body>{children}</body>
    </html>
  );
} 